/**
 * Pregnancy → Vaccination Workflow Service
 *
 * When a pregnancy is confirmed, this service automatically creates
 * vaccination reminder records at the two pre-calving milestones:
 *   • Dry-Off Vaccination        (EDD − 60 days)
 *   • Pre-Calving Vaccination    (EDD − 30 days)
 *
 * Status is derived dynamically at read-time by vaccination-status.ts from
 * each record's `next_due_date` vs. today — no cron job is needed to
 * transition records between Pending / Due / Overdue states.
 *
 * All auto-generated records carry source = "pregnancy_workflow" and a
 * pregnancy_id FK so they can be cancelled / updated atomically when the
 * pregnancy is cancelled, deleted, or its EDD changes.
 */

import { prisma } from "@/lib/db";

export const WORKFLOW_SOURCE = "pregnancy_workflow";

// ─── Species gestation period lookup ────────────────────────────────────────
// The species table doesn't have a gestation_period_days column; we use a
// name-based lookup with a sensible dairy-cow default.
const GESTATION_DAYS_BY_SPECIES: Record<string, number> = {
  Cattle: 283,
  Cow: 283,
  Dairy: 283,
  Buffalo: 310,
  Sheep: 147,
  Ovine: 147,
  Goat: 150,
  Caprine: 150,
  Pig: 114,
  Swine: 114,
  Horse: 340,
  Equine: 340,
  Camel: 390,
  Deer: 230,
  Llama: 350,
  Alpaca: 345,
};

function resolveGestationDays(speciesName: string | null | undefined): number {
  if (!speciesName) return 283;
  const lower = speciesName.toLowerCase();
  for (const [key, days] of Object.entries(GESTATION_DAYS_BY_SPECIES)) {
    if (lower.includes(key.toLowerCase())) return days;
  }
  return 283;
}

// ─── Milestone definitions ───────────────────────────────────────────────────
interface Milestone {
  vaccineName: string;
  daysFromEdd: number; // negative = before EDD
  noteTemplate: (eddStr: string) => string;
}

const MILESTONES: Milestone[] = [
  {
    vaccineName: "Dry-Off Vaccination",
    daysFromEdd: -60,
    noteTemplate: (edd) =>
      `Auto-generated by Pregnancy Workflow. Dry-Off vaccination scheduled 60 days before expected delivery (${edd}). Administer at dry-off to protect against mastitis and metabolic disorders.`,
  },
  {
    vaccineName: "Pre-Calving Vaccination",
    daysFromEdd: -30,
    noteTemplate: (edd) =>
      `Auto-generated by Pregnancy Workflow. Pre-Calving vaccination scheduled 30 days before expected delivery (${edd}). Provides passive immunity transfer to the calf via colostrum.`,
  },
];

function addDays(date: Date, days: number): Date {
  const d = new Date(date);
  d.setUTCDate(d.getUTCDate() + days);
  return d;
}

function toDateOnly(d: Date): string {
  return d.toISOString().slice(0, 10);
}

// ─── Core workflow functions ─────────────────────────────────────────────────

/**
 * Called when a pregnancy is confirmed for the first time.
 * Idempotent — duplicate records are skipped via a dedup check.
 */
export async function triggerWorkflow(
  pregnancyId: number,
  animalId: number,
  inseminationDate: Date,
  expectedDeliveryDate: Date | null,
): Promise<void> {
  // Resolve EDD: use provided date or fall back to insemination + gestation
  let edd = expectedDeliveryDate;
  if (!edd) {
    const animal = await prisma.animals.findUnique({
      where: { animal_id: animalId },
      include: { breeds: { include: { species: true } } },
    });
    const days = resolveGestationDays(animal?.breeds?.species?.species_name);
    edd = addDays(inseminationDate, days);
  }

  const eddStr = toDateOnly(edd);

  // Load the animal label for notifications
  const animal = await prisma.animals.findUnique({
    where: { animal_id: animalId },
    select: { tag_number: true, animal_name: true },
  });
  const animalLabel = animal
    ? `#${animal.tag_number}${animal.animal_name ? ` (${animal.animal_name})` : ""}`
    : `Animal #${animalId}`;

  const created: string[] = [];

  for (const milestone of MILESTONES) {
    const scheduledDate = addDays(edd, milestone.daysFromEdd);

    // Deduplication: skip if a workflow record already exists for this
    // pregnancy + vaccine combination (regardless of date changes).
    const existing = await prisma.vaccination_records.findFirst({
      where: {
        pregnancy_id: pregnancyId,
        vaccine_name: milestone.vaccineName,
        source: WORKFLOW_SOURCE,
      },
    });
    if (existing) continue;

    await prisma.vaccination_records.create({
      data: {
        animal_id: animalId,
        pregnancy_id: pregnancyId,
        vaccine_name: milestone.vaccineName,
        vaccination_date: null, // not yet administered
        next_due_date: scheduledDate,
        source: WORKFLOW_SOURCE,
        notes: milestone.noteTemplate(eddStr),
      },
    });

    created.push(
      `${milestone.vaccineName} on ${toDateOnly(scheduledDate)}`,
    );
  }

  if (created.length === 0) return; // all already existed — nothing to notify

  // Notify all admins / managers / vets
  const recipients = await prisma.users.findMany({
    where: { role: { in: ["ADMIN", "FARM_MANAGER", "VETERINARIAN"] }, is_active: true },
    select: { user_id: true },
  });

  const summary = created.join(" · ");
  const notifData = recipients.map((u) => ({
    user_id: u.user_id,
    type: "PREGNANCY_WORKFLOW",
    title: "Vaccination Reminders Auto-Created",
    message: `${animalLabel} confirmed pregnant (EDD: ${eddStr}). Auto-scheduled: ${summary}.`,
    entity_type: "pregnancy",
    entity_id: pregnancyId,
  }));

  if (notifData.length > 0) {
    await prisma.notifications.createMany({ data: notifData });
  }
}

/**
 * Called when a pregnancy is cancelled, marked Failed, or deleted.
 * Deletes auto-generated vaccination records that have not yet been
 * administered (vaccination_date IS NULL). Administered records are kept
 * as historical data.
 *
 * Returns the count of deleted records.
 */
export async function cancelWorkflow(pregnancyId: number): Promise<number> {
  const { count } = await prisma.vaccination_records.deleteMany({
    where: {
      pregnancy_id: pregnancyId,
      source: WORKFLOW_SOURCE,
      vaccination_date: null,
    },
  });
  return count;
}

/**
 * Called when the Expected Delivery Date of a confirmed pregnancy changes.
 * Updates `next_due_date` on all pending auto-generated records proportionally.
 * Administered records are left untouched.
 */
export async function updateWorkflowDates(
  pregnancyId: number,
  newExpectedDeliveryDate: Date,
): Promise<void> {
  const pending = await prisma.vaccination_records.findMany({
    where: {
      pregnancy_id: pregnancyId,
      source: WORKFLOW_SOURCE,
      vaccination_date: null,
    },
    select: { vaccination_id: true, vaccine_name: true },
  });

  for (const record of pending) {
    const milestone = MILESTONES.find((m) => m.vaccineName === record.vaccine_name);
    if (!milestone) continue;

    const newScheduledDate = addDays(newExpectedDeliveryDate, milestone.daysFromEdd);

    await prisma.vaccination_records.update({
      where: { vaccination_id: record.vaccination_id },
      data: {
        next_due_date: newScheduledDate,
        notes: milestone.noteTemplate(toDateOnly(newExpectedDeliveryDate)),
      },
    });
  }
}
